[metadata]
name = jarn.mkrelease
version = 6.2
description = Python package releaser
long_description = file: README.rst, CHANGES.rst
long_description_content_type = text/x-rst
classifiers =
    Development Status :: 5 - Production/Stable
    Environment :: Console
    Intended Audience :: Developers
    Operating System :: MacOS :: MacOS X
    Operating System :: POSIX
    Programming Language :: Python
    Programming Language :: Python :: 3
keywords = create, release, upload, python, sdist, sdists, wheel, wheels, pypi, releaser, package, packages, publish
author = Stefan H. Holek
author_email = stefan@epy.co.at
url = https://github.com/Jarn/jarn.mkrelease
license = BSD-2-Clause

[options]
packages =
    jarn
    jarn.mkrelease
zip_safe = false
install_requires =
    setuptools >= 75.3.4
    lazy >= 1.6
    wheel >= 0.45.1
    termcolor >= 2.4.0
python_requires = >=3.8

[options.entry_points]
console_scripts =
    mkrelease = jarn.mkrelease.mkrelease:main

[options.extras_require]
testing =
    nose2 >= 0.15.1
    nose2-kflag >= 1.0
twine =
    twine >= 6.1.0
filefinder =
    setuptools-subversion >= 3.1
    setuptools-hg >= 0.4
    setuptools-git >= 1.2

[egg_info]
tag_build = dev0
